vtex:
  schema: https
  tokenSchema: http
  url: "cencosud.vridge.io"
  port: "443"
  tokenPort: "2000"
  grantType: "client_credentials"
  clientId: "bd986b7fe30b11e6916106831df067a8"
  clientSecret: "bd986b95e30b11e6916106831df067a8"
security:
  require-ssl: true
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb
      
endpoints:
    enabled: false
    health:
        enabled: true