vtex:
  schema: http
  url: "jumbochilehomolog.vtexcommercestable.com.br"
  port: "80"
  apiKey: "ignacio.contreras.cencosud@gmail.com"
  apiSecret: "8P9HJ8Sr"
  env: qa
  urlImages: "https://jumbochilehomolog.vteximg.com.br/arquivos/"
mongoConfig:
  database: "jcl_categories"
business:
  specsRemove: 
    - "Modal 90 minutos"
  departmentsIds:
    - "1"
    - "2"
    - "4"
    - "15"
    - "16"
    - "31"
    - "79"
    - "123"
    - "137"
    - "151"
    - "153"
    - "158"
    - "176"
    - "199"
    - "200"
    - "232"
    - "263"
    - "274"
    - "293"
    - "354"
    - "362"
    - "382"
    - "65"

  departments:
    1: {id: "1", name: "Lácteos y Bebidas Vegetales", basicPath: "/lacteos-y-beb--vegetal", order: "0", food: true}
    4: {id: "4", name: "Frutas y Verduras", basicPath: "/frutas-y-verduras", order: "1", food: true}
    31: {id: "31", name: "Despensa", basicPath: "/despensa", order: "2", food: true}
    65: {id: "65", name: "Desayuno y Dulces", basicPath: "/desayuno-y-dulces", order: "3", food: true}
    16: {id: "16", name: "Quesos y Fiambres", basicPath: "/quesos-y-fiambres", order: "4", food: true}
    2: {id: "2", name: "Carnes Rojas", basicPath: "/carnes-rojas", order: "5", food: true}
    123: {id: "123", name: "Pollo y Pavo", basicPath: "/pollo-y-pavo", order: "6", food: true}
    153: {id: "153", name: "Pescadería", basicPath: "/pescaderia", order: "7", food: true}
    158: {id: "158", name: "Congelados", basicPath: "/congelados", order: "8", food: true}
    232: {id: "232", name: "Panadería y Pastelería", basicPath: "/panaderia-y-pasteleria", order: "9", food: true}
    274: {id: "274", name: "Platos Preparados", basicPath: "/platos-preparados", order: "10", food: true}
    151: {id: "151", name: "Bebidas y Jugos", basicPath: "/bebidas-y-jugos", order: "11", food: true}
    200: {id: "200", name: "Vinos y Licores", basicPath: "/vinos-y-licores", order: "12", food: true}
    293: {id: "293", name: "Perfumería", basicPath: "/perfumeria", order: "13", food: true}
    15: {id: "15", name: "Limpieza", basicPath: "/limpieza", order: "14", food: true}    
    354: {id: "354", name: "Farmacia", basicPath: "/farmacia", order: "15", food: true}
    362: {id: "362", name: "Come Libre", basicPath: "/come-libre", order: "16", food: true}
    79: {id: "79", name: "Tecnología", basicPath: "/tecnologia", order: "17", food: false}
    137: {id: "137", name: "Electrohogar", basicPath: "/electrohogar", order: "18", food: false}
    199: {id: "199", name: "Juguetería y Librería", basicPath: "/jugueteria-y-libreria", order: "19", food: false}    
    263: {id: "263", name: "Hogar", basicPath: "/hogar", order: "20", food: false}
    382: {id: "382", name: "Mi bebé", basicPath: "/mi-bebe", order: "21", food: false}
    176: {id: "176", name: "Mascotas", basicPath: "/mascotas", order: "22", food: false}
    
    
  departmentDeals: "ofertas"
  dealClusterId: "136"

server:
  path: "https://jcldev-category-service.mybluemix.net/"
security:
  require-ssl: true
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb
      
endpoints:
    enabled: false
    health:
        enabled: true