vtex:
  schema: http
  url: "jumbo.vtexcommercestable.com.br"
  port: "80"
  apiKey: "vtexappkey-jumbo-DEYICH"
  apiSecret: "MWDTHGQLSKANIZPSYXQCXBVNKAYDWNWNLYBFGXQELAHMCSIRPACEDYPKBQIHINPFOMCKXJLBGMQXUILRSGNWKRKMIQDQOJWYLBYPQYTGOBXQISQSFQPBZTUWCQCHFVMX"
  env: prod
  urlImages: "https://jumbo.vteximg.com.br/arquivos/"
mongoConfig:
  database: "jcl_categories"
business:
  specsRemove: 
    - "Modal 90 minutos"
  departmentsIds:
    - "1"
    - "75"
    - "20"
    - "261"
    - "86"
    - "27"
    - "298"
    - "107"
    - "316"
    - "189"
    - "124"
    - "127"
    - "400"
    - "335"
    - "204"
    - "157"
    - "354"
    - "183"
    - "230"
    - "222"
    - "292"
    - "393"
    - "61"

  departments:
    1: {id: "1", name: "Lácteos y Bebidas Vegetales", basicPath: "/lacteos-y-bebidas-vegetales", order: "0",  food: true}
    20: {id: "20", name: "Frutas y Verduras", basicPath: "/frutas-y-verduras", order: "1", food: true}
    27: {id: "27", name: "Despensa", basicPath: "/despensa", order: "2", food: true}
    61: {id: "61", name: "Desayuno y Dulces", basicPath: "/desayuno-y-dulces", order: "3", food: true}
    86: {id: "86", name: "Quesos y Fiambres", basicPath: "/quesos-y-fiambres", order: "4",  food: true}
    75: {id: "75", name: "Carnes Rojas", basicPath: "/carnes-rojas", order: "5", food: true}
    107: {id: "107", name: "Pollo y Pavo", basicPath: "/pollo-y-pavo", order: "6", food: true}
    124: {id: "124", name: "Pescadería", basicPath: "/pescaderia", order: "7", food: true}
    127: {id: "127", name: "Congelados", basicPath: "/congelados", order: "8", food: true}
    157: {id: "157", name: "Panadería y Pastelería", basicPath: "/panaderia-y-pasteleria", order: "9", food: true}
    183: {id: "183", name: "Platos Preparados", basicPath: "/platos-preparados", order: "10", food: true}
    189: {id: "189", name: "Bebidas y Jugos", basicPath: "/bebidas-aguas-y-jugos", order: "11",  food: true}
    204: {id: "204", name: "Vinos y Licores", basicPath: "/vinos-cervezas-y-licores", order: "12", food: true}
    230: {id: "230", name: "Perfumería", basicPath: "/perfumeria", order: "13", food: true}
    261: {id: "261", name: "Limpieza", basicPath: "/limpieza", order: "14", food: true}
    222: {id: "222", name: "Farmacia", basicPath: "/farmacia", order: "15", food: true}
    292: {id: "292", name: "Come Libre", basicPath: "/come-libre", order: "16", food: true}
    400: {id: "400", name: "Mascotas", basicPath: "/mascotas", order: "17", food: false}
    316: {id: "316", name: "Electrohogar", basicPath: "/electrohogar", order: "18", food: false}
    298: {id: "298", name: "Tecnología", basicPath: "/tecnologia", order: "19", food: false}
    335: {id: "335", name: "Juguetería y Librería", basicPath: "/jugueteria-y-libreria", order: "20", food: false}
    354: {id: "354", name: "Hogar", basicPath: "/hogar", order: "21", food: false}
    393: {id: "393", name: "Mi bebé", basicPath: "/mi-bebe", order: "22", food: false}
    
  departmentDeals: "ofertas"
  dealClusterId: "136"

server:
  path: "https://jcluat-category-service.mybluemix.net/"
security:
  require-ssl: true
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb
      
endpoints:
    enabled: false
    health:
        enabled: true