rewards:
  schema: http
  url: "https://cap-sg-prd-5.integration.ibmcloud.com:18006/cencosud_des/servlet/awscdcen"
  port: "80"
security:
  require-ssl: true
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb
          
endpoints:
    enabled: false
    health:
        enabled: true
client:
  default-uri: https://cap-sg-prd-5.integration.ibmcloud.com:18006/cencosud_des/servlet/awscdcen
  ssl:
    trust-store: classpath:static/certs/dev/key.jks
    trust-store-password: rewards