rewards:
  schema: http
  url: "https://cap-sg-prd-3.integration.ibmcloud.com:16636/cencosud/servlet/awscdcen"
  port: "80"
security:
  require-ssl: true
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb

endpoints:
    enabled: false
    health:
        enabled: true