#Sales Chanel delivery mode
salesChannelMe:
  1:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  2:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  3:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  4:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  5:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  6:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  7:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  8:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  9:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  10:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  11:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  12:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  13:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  14:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  15:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  16:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: false
    - id: 114
      name: "Retira en tu auto"
      enabled: true
  17:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  18:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  19:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
  20:
    - id: 111
      name: "Recibe en tu casa"
      enabled: false
    - id: 112
      name: "Enviamos tu compra en 90 min"
      enabled: false
    - id: 113
      name: "Retira en el local"
      enabled: true
    - id: 114
      name: "Retira en tu auto"
      enabled: false
#Default delivery type
listDeliveryType:
  - id: 111
    name: "Recibe en tu casa"
  - id: 112
    name: "Enviamos tu compra en 90 min"
  - id: 113
    name: "Retira en el local"
  - id: 114
    name: "Retira en tu auto"  
  