vtex:
  schema: http
  url: "api.vtexcrm.com.br/jumbochilehomolog"
  port: "80"
  apiKey: "vtexappkey-jumbochilehomolog-IAMKWV"
  apiSecret: "RSRVBUIUVTMVEPPXIRIWPYWEIYSJQHSTWYPASGFFFRASOZDBBYCGWOYTWMNDBYENASZFAOFCMCRXXEPJURHREMXHAWEFSBDGNMRWZYBNTZTTWBVSWDJKQMJOVRFDKZJK"
security:
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb