vtex:
  schema: http
  url: "api.vtexcrm.com.br/jumbo"
  port: "80"
  apiKey: "vtexappkey-jumbo-DEYICH"
  apiSecret: "MWDTHGQLSKANIZPSYXQCXBVNKAYDWNWNLYBFGXQELAHMCSIRPACEDYPKBQIHINPFOMCKXJLBGMQXUILRSGNWKRKMIQDQOJWYLBYPQYTGOBXQISQSFQPBZTUWCQCHFVMX"
security:
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb
