//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 04:53:43 PM CDT 
//


package com.cencosud.middleware.bonus.client.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EBMType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EBMType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://xmlns.cencosud.corp/Core/EBM/Common/EBM}EBMHeader"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EBMType", namespace = "http://xmlns.cencosud.corp/Core/EBM/Common/EBM", propOrder = {
    "ebmHeader"
})
@XmlSeeAlso({
    QueryMemberSegmentsRequestEBMType.class,
    QueryLoyaltyMemberRequestEBMType.class,
    QueryLoyaltyMemberFullRequestEBMType.class,
    EnrolLoyaltyMemberRequestEBMType.class,
    UpdateLoyaltyMemberRequestEBMType.class,
    QueryLoyaltyMemberIdByDNIRequestEBMType.class
})
public class EBMType {

    @XmlElement(name = "EBMHeader", required = true)
    protected EBMHeaderType ebmHeader;

    /**
     * Gets the value of the ebmHeader property.
     * 
     * @return
     *     possible object is
     *     {@link EBMHeaderType }
     *     
     */
    public EBMHeaderType getEBMHeader() {
        return ebmHeader;
    }

    /**
     * Sets the value of the ebmHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link EBMHeaderType }
     *     
     */
    public void setEBMHeader(EBMHeaderType value) {
        this.ebmHeader = value;
    }

}
