//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 04:53:43 PM CDT 
//


package com.cencosud.middleware.bonus.client.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoyaltyMemberFullType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoyaltyMemberFullType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LoyaltyMember" type="{http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember}MemberType"/&gt;
 *         &lt;element name="MemberPreferences" type="{http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember}MemberPreferencesType" minOccurs="0"/&gt;
 *         &lt;element name="MemberSurvey" type="{http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember}MemberSurveyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoyaltyMemberFullType", namespace = "http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember", propOrder = {
    "loyaltyMember",
    "memberPreferences",
    "memberSurvey"
})
public class LoyaltyMemberFullType {

    @XmlElement(name = "LoyaltyMember", required = true)
    protected MemberType loyaltyMember;
    @XmlElement(name = "MemberPreferences")
    protected MemberPreferencesType memberPreferences;
    @XmlElement(name = "MemberSurvey")
    protected MemberSurveyType memberSurvey;

    /**
     * Gets the value of the loyaltyMember property.
     * 
     * @return
     *     possible object is
     *     {@link MemberType }
     *     
     */
    public MemberType getLoyaltyMember() {
        return loyaltyMember;
    }

    /**
     * Sets the value of the loyaltyMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberType }
     *     
     */
    public void setLoyaltyMember(MemberType value) {
        this.loyaltyMember = value;
    }

    /**
     * Gets the value of the memberPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link MemberPreferencesType }
     *     
     */
    public MemberPreferencesType getMemberPreferences() {
        return memberPreferences;
    }

    /**
     * Sets the value of the memberPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberPreferencesType }
     *     
     */
    public void setMemberPreferences(MemberPreferencesType value) {
        this.memberPreferences = value;
    }

    /**
     * Gets the value of the memberSurvey property.
     * 
     * @return
     *     possible object is
     *     {@link MemberSurveyType }
     *     
     */
    public MemberSurveyType getMemberSurvey() {
        return memberSurvey;
    }

    /**
     * Sets the value of the memberSurvey property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberSurveyType }
     *     
     */
    public void setMemberSurvey(MemberSurveyType value) {
        this.memberSurvey = value;
    }

}
