//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 04:53:43 PM CDT 
//


package com.cencosud.middleware.bonus.client.wsdl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MemberType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MemberType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EnrolmentChannel" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Batch"/&gt;
 *               &lt;enumeration value="POS"/&gt;
 *               &lt;enumeration value="Portal"/&gt;
 *               &lt;enumeration value="MSR"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EnrolmentLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isParent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ParentMemberId" type="{http://xmlns.cencosud.corp/Loyalty/LoyCommonTypes}MemberIdentifierType" minOccurs="0"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastName2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MemberId" type="{http://xmlns.cencosud.corp/Loyalty/LoyCommonTypes}MemberIdentifierType" minOccurs="0"/&gt;
 *         &lt;element name="Email" type="{http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember}StringValidType" minOccurs="0"/&gt;
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MobilePhone" type="{http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember}StringValidType" minOccurs="0"/&gt;
 *         &lt;element name="HomePhone" type="{http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember}StringValidType" minOccurs="0"/&gt;
 *         &lt;element name="MobilePhone2" type="{http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember}StringValidType" minOccurs="0"/&gt;
 *         &lt;element name="ComercialPhone" type="{http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember}StringValidType" minOccurs="0"/&gt;
 *         &lt;element name="MaritalStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PreferedPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RedeemPermissions" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SubStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Address" type="{http://xmlns.cencosud.corp/Loyalty/LoyCommonTypes}AddressType" minOccurs="0"/&gt;
 *         &lt;element name="Points" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="AcceptedTC" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Segment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Segment1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ValidationPending" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalProfileMember" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MemberType", namespace = "http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember", propOrder = {
    "enrolmentChannel",
    "enrolmentLocation",
    "isParent",
    "parentMemberId",
    "name",
    "lastName",
    "lastName2",
    "memberId",
    "email",
    "birthDate",
    "password",
    "gender",
    "mobilePhone",
    "homePhone",
    "mobilePhone2",
    "comercialPhone",
    "maritalStatus",
    "preferedPhone",
    "redeemPermissions",
    "status",
    "subStatus",
    "address",
    "points",
    "acceptedTC",
    "segment",
    "segment1",
    "validationPending",
    "additionalProfileMember"
})
public class MemberType {

    @XmlElement(name = "EnrolmentChannel")
    protected String enrolmentChannel;
    @XmlElement(name = "EnrolmentLocation")
    protected String enrolmentLocation;
    protected Boolean isParent;
    @XmlElement(name = "ParentMemberId")
    protected MemberIdentifierType parentMemberId;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "LastName2")
    protected String lastName2;
    @XmlElement(name = "MemberId")
    protected MemberIdentifierType memberId;
    @XmlElement(name = "Email")
    protected StringValidType email;
    @XmlElement(name = "BirthDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(name = "Password")
    protected String password;
    @XmlElement(name = "Gender")
    protected String gender;
    @XmlElement(name = "MobilePhone")
    protected StringValidType mobilePhone;
    @XmlElement(name = "HomePhone")
    protected StringValidType homePhone;
    @XmlElement(name = "MobilePhone2")
    protected StringValidType mobilePhone2;
    @XmlElement(name = "ComercialPhone")
    protected StringValidType comercialPhone;
    @XmlElement(name = "MaritalStatus")
    protected String maritalStatus;
    @XmlElement(name = "PreferedPhone")
    protected String preferedPhone;
    @XmlElement(name = "RedeemPermissions")
    protected Boolean redeemPermissions;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "SubStatus")
    protected String subStatus;
    @XmlElement(name = "Address")
    protected AddressType address;
    @XmlElement(name = "Points")
    protected BigInteger points;
    @XmlElement(name = "AcceptedTC")
    protected Boolean acceptedTC;
    @XmlElement(name = "Segment")
    protected String segment;
    @XmlElement(name = "Segment1")
    protected String segment1;
    @XmlElement(name = "ValidationPending")
    protected Boolean validationPending;
    @XmlElement(name = "AdditionalProfileMember")
    protected Boolean additionalProfileMember;

    /**
     * Gets the value of the enrolmentChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrolmentChannel() {
        return enrolmentChannel;
    }

    /**
     * Sets the value of the enrolmentChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrolmentChannel(String value) {
        this.enrolmentChannel = value;
    }

    /**
     * Gets the value of the enrolmentLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrolmentLocation() {
        return enrolmentLocation;
    }

    /**
     * Sets the value of the enrolmentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrolmentLocation(String value) {
        this.enrolmentLocation = value;
    }

    /**
     * Gets the value of the isParent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsParent() {
        return isParent;
    }

    /**
     * Sets the value of the isParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsParent(Boolean value) {
        this.isParent = value;
    }

    /**
     * Gets the value of the parentMemberId property.
     * 
     * @return
     *     possible object is
     *     {@link MemberIdentifierType }
     *     
     */
    public MemberIdentifierType getParentMemberId() {
        return parentMemberId;
    }

    /**
     * Sets the value of the parentMemberId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberIdentifierType }
     *     
     */
    public void setParentMemberId(MemberIdentifierType value) {
        this.parentMemberId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the lastName2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName2() {
        return lastName2;
    }

    /**
     * Sets the value of the lastName2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName2(String value) {
        this.lastName2 = value;
    }

    /**
     * Gets the value of the memberId property.
     * 
     * @return
     *     possible object is
     *     {@link MemberIdentifierType }
     *     
     */
    public MemberIdentifierType getMemberId() {
        return memberId;
    }

    /**
     * Sets the value of the memberId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberIdentifierType }
     *     
     */
    public void setMemberId(MemberIdentifierType value) {
        this.memberId = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link StringValidType }
     *     
     */
    public StringValidType getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValidType }
     *     
     */
    public void setEmail(StringValidType value) {
        this.email = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the mobilePhone property.
     * 
     * @return
     *     possible object is
     *     {@link StringValidType }
     *     
     */
    public StringValidType getMobilePhone() {
        return mobilePhone;
    }

    /**
     * Sets the value of the mobilePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValidType }
     *     
     */
    public void setMobilePhone(StringValidType value) {
        this.mobilePhone = value;
    }

    /**
     * Gets the value of the homePhone property.
     * 
     * @return
     *     possible object is
     *     {@link StringValidType }
     *     
     */
    public StringValidType getHomePhone() {
        return homePhone;
    }

    /**
     * Sets the value of the homePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValidType }
     *     
     */
    public void setHomePhone(StringValidType value) {
        this.homePhone = value;
    }

    /**
     * Gets the value of the mobilePhone2 property.
     * 
     * @return
     *     possible object is
     *     {@link StringValidType }
     *     
     */
    public StringValidType getMobilePhone2() {
        return mobilePhone2;
    }

    /**
     * Sets the value of the mobilePhone2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValidType }
     *     
     */
    public void setMobilePhone2(StringValidType value) {
        this.mobilePhone2 = value;
    }

    /**
     * Gets the value of the comercialPhone property.
     * 
     * @return
     *     possible object is
     *     {@link StringValidType }
     *     
     */
    public StringValidType getComercialPhone() {
        return comercialPhone;
    }

    /**
     * Sets the value of the comercialPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValidType }
     *     
     */
    public void setComercialPhone(StringValidType value) {
        this.comercialPhone = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the preferedPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferedPhone() {
        return preferedPhone;
    }

    /**
     * Sets the value of the preferedPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferedPhone(String value) {
        this.preferedPhone = value;
    }

    /**
     * Gets the value of the redeemPermissions property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRedeemPermissions() {
        return redeemPermissions;
    }

    /**
     * Sets the value of the redeemPermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRedeemPermissions(Boolean value) {
        this.redeemPermissions = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the subStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubStatus() {
        return subStatus;
    }

    /**
     * Sets the value of the subStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubStatus(String value) {
        this.subStatus = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the points property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPoints() {
        return points;
    }

    /**
     * Sets the value of the points property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPoints(BigInteger value) {
        this.points = value;
    }

    /**
     * Gets the value of the acceptedTC property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAcceptedTC() {
        return acceptedTC;
    }

    /**
     * Sets the value of the acceptedTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAcceptedTC(Boolean value) {
        this.acceptedTC = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment(String value) {
        this.segment = value;
    }

    /**
     * Gets the value of the segment1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment1() {
        return segment1;
    }

    /**
     * Sets the value of the segment1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment1(String value) {
        this.segment1 = value;
    }

    /**
     * Gets the value of the validationPending property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isValidationPending() {
        return validationPending;
    }

    /**
     * Sets the value of the validationPending property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setValidationPending(Boolean value) {
        this.validationPending = value;
    }

    /**
     * Gets the value of the additionalProfileMember property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAdditionalProfileMember() {
        return additionalProfileMember;
    }

    /**
     * Sets the value of the additionalProfileMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdditionalProfileMember(Boolean value) {
        this.additionalProfileMember = value;
    }

}
