//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 04:53:43 PM CDT 
//


package com.cencosud.middleware.bonus.client.wsdl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MemberSurveyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MemberSurveyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NumberOfPeopleAtHome" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfChildren" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="AgeOfChild1" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="AgeOfChild2" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="AgeOfChild3" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="AgeOfChild4" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="CreditCardMostUsed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PetrolStationMostUsed" type="{http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember}ListOfAnswerType" minOccurs="0"/&gt;
 *         &lt;element name="AmountSpendedOnGasolineMonth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MobileCompanyUsed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PreferedPharmacy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PreferredSupermarket" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OtherLoyaltyPrograms" type="{http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember}ListOfAnswerType" minOccurs="0"/&gt;
 *         &lt;element name="RegularNewspaper" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StudiesLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Home" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PhoneTypeContract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CategoryOfOwnCompany" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NumberOfCars" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="BirthYearChild1" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="BirthYearChild2" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="BirthYearChild3" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="BirthYearChild4" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalMemberFor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MemberSurveyType", namespace = "http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember", propOrder = {
    "numberOfPeopleAtHome",
    "numberOfChildren",
    "ageOfChild1",
    "ageOfChild2",
    "ageOfChild3",
    "ageOfChild4",
    "creditCardMostUsed",
    "petrolStationMostUsed",
    "amountSpendedOnGasolineMonth",
    "mobileCompanyUsed",
    "preferedPharmacy",
    "preferredSupermarket",
    "otherLoyaltyPrograms",
    "regularNewspaper",
    "studiesLevel",
    "home",
    "phoneTypeContract",
    "categoryOfOwnCompany",
    "numberOfCars",
    "birthYearChild1",
    "birthYearChild2",
    "birthYearChild3",
    "birthYearChild4",
    "additionalMemberFor"
})
public class MemberSurveyType {

    @XmlElement(name = "NumberOfPeopleAtHome")
    protected BigInteger numberOfPeopleAtHome;
    @XmlElement(name = "NumberOfChildren")
    protected BigInteger numberOfChildren;
    @XmlElement(name = "AgeOfChild1")
    protected BigInteger ageOfChild1;
    @XmlElement(name = "AgeOfChild2")
    protected BigInteger ageOfChild2;
    @XmlElement(name = "AgeOfChild3")
    protected BigInteger ageOfChild3;
    @XmlElement(name = "AgeOfChild4")
    protected BigInteger ageOfChild4;
    @XmlElement(name = "CreditCardMostUsed")
    protected String creditCardMostUsed;
    @XmlElement(name = "PetrolStationMostUsed")
    protected ListOfAnswerType petrolStationMostUsed;
    @XmlElement(name = "AmountSpendedOnGasolineMonth")
    protected String amountSpendedOnGasolineMonth;
    @XmlElement(name = "MobileCompanyUsed")
    protected String mobileCompanyUsed;
    @XmlElement(name = "PreferedPharmacy")
    protected String preferedPharmacy;
    @XmlElement(name = "PreferredSupermarket")
    protected String preferredSupermarket;
    @XmlElement(name = "OtherLoyaltyPrograms")
    protected ListOfAnswerType otherLoyaltyPrograms;
    @XmlElement(name = "RegularNewspaper")
    protected String regularNewspaper;
    @XmlElement(name = "StudiesLevel")
    protected String studiesLevel;
    @XmlElement(name = "Home")
    protected String home;
    @XmlElement(name = "PhoneTypeContract")
    protected String phoneTypeContract;
    @XmlElement(name = "CategoryOfOwnCompany")
    protected String categoryOfOwnCompany;
    @XmlElement(name = "NumberOfCars")
    protected BigInteger numberOfCars;
    @XmlElement(name = "BirthYearChild1")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthYearChild1;
    @XmlElement(name = "BirthYearChild2")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthYearChild2;
    @XmlElement(name = "BirthYearChild3")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthYearChild3;
    @XmlElement(name = "BirthYearChild4")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthYearChild4;
    @XmlElement(name = "AdditionalMemberFor")
    protected String additionalMemberFor;

    /**
     * Gets the value of the numberOfPeopleAtHome property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfPeopleAtHome() {
        return numberOfPeopleAtHome;
    }

    /**
     * Sets the value of the numberOfPeopleAtHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfPeopleAtHome(BigInteger value) {
        this.numberOfPeopleAtHome = value;
    }

    /**
     * Gets the value of the numberOfChildren property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfChildren() {
        return numberOfChildren;
    }

    /**
     * Sets the value of the numberOfChildren property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfChildren(BigInteger value) {
        this.numberOfChildren = value;
    }

    /**
     * Gets the value of the ageOfChild1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgeOfChild1() {
        return ageOfChild1;
    }

    /**
     * Sets the value of the ageOfChild1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgeOfChild1(BigInteger value) {
        this.ageOfChild1 = value;
    }

    /**
     * Gets the value of the ageOfChild2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgeOfChild2() {
        return ageOfChild2;
    }

    /**
     * Sets the value of the ageOfChild2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgeOfChild2(BigInteger value) {
        this.ageOfChild2 = value;
    }

    /**
     * Gets the value of the ageOfChild3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgeOfChild3() {
        return ageOfChild3;
    }

    /**
     * Sets the value of the ageOfChild3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgeOfChild3(BigInteger value) {
        this.ageOfChild3 = value;
    }

    /**
     * Gets the value of the ageOfChild4 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgeOfChild4() {
        return ageOfChild4;
    }

    /**
     * Sets the value of the ageOfChild4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgeOfChild4(BigInteger value) {
        this.ageOfChild4 = value;
    }

    /**
     * Gets the value of the creditCardMostUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditCardMostUsed() {
        return creditCardMostUsed;
    }

    /**
     * Sets the value of the creditCardMostUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditCardMostUsed(String value) {
        this.creditCardMostUsed = value;
    }

    /**
     * Gets the value of the petrolStationMostUsed property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfAnswerType }
     *     
     */
    public ListOfAnswerType getPetrolStationMostUsed() {
        return petrolStationMostUsed;
    }

    /**
     * Sets the value of the petrolStationMostUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfAnswerType }
     *     
     */
    public void setPetrolStationMostUsed(ListOfAnswerType value) {
        this.petrolStationMostUsed = value;
    }

    /**
     * Gets the value of the amountSpendedOnGasolineMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmountSpendedOnGasolineMonth() {
        return amountSpendedOnGasolineMonth;
    }

    /**
     * Sets the value of the amountSpendedOnGasolineMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmountSpendedOnGasolineMonth(String value) {
        this.amountSpendedOnGasolineMonth = value;
    }

    /**
     * Gets the value of the mobileCompanyUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileCompanyUsed() {
        return mobileCompanyUsed;
    }

    /**
     * Sets the value of the mobileCompanyUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileCompanyUsed(String value) {
        this.mobileCompanyUsed = value;
    }

    /**
     * Gets the value of the preferedPharmacy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferedPharmacy() {
        return preferedPharmacy;
    }

    /**
     * Sets the value of the preferedPharmacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferedPharmacy(String value) {
        this.preferedPharmacy = value;
    }

    /**
     * Gets the value of the preferredSupermarket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredSupermarket() {
        return preferredSupermarket;
    }

    /**
     * Sets the value of the preferredSupermarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredSupermarket(String value) {
        this.preferredSupermarket = value;
    }

    /**
     * Gets the value of the otherLoyaltyPrograms property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfAnswerType }
     *     
     */
    public ListOfAnswerType getOtherLoyaltyPrograms() {
        return otherLoyaltyPrograms;
    }

    /**
     * Sets the value of the otherLoyaltyPrograms property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfAnswerType }
     *     
     */
    public void setOtherLoyaltyPrograms(ListOfAnswerType value) {
        this.otherLoyaltyPrograms = value;
    }

    /**
     * Gets the value of the regularNewspaper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegularNewspaper() {
        return regularNewspaper;
    }

    /**
     * Sets the value of the regularNewspaper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegularNewspaper(String value) {
        this.regularNewspaper = value;
    }

    /**
     * Gets the value of the studiesLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudiesLevel() {
        return studiesLevel;
    }

    /**
     * Sets the value of the studiesLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudiesLevel(String value) {
        this.studiesLevel = value;
    }

    /**
     * Gets the value of the home property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHome() {
        return home;
    }

    /**
     * Sets the value of the home property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHome(String value) {
        this.home = value;
    }

    /**
     * Gets the value of the phoneTypeContract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneTypeContract() {
        return phoneTypeContract;
    }

    /**
     * Sets the value of the phoneTypeContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneTypeContract(String value) {
        this.phoneTypeContract = value;
    }

    /**
     * Gets the value of the categoryOfOwnCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryOfOwnCompany() {
        return categoryOfOwnCompany;
    }

    /**
     * Sets the value of the categoryOfOwnCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryOfOwnCompany(String value) {
        this.categoryOfOwnCompany = value;
    }

    /**
     * Gets the value of the numberOfCars property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfCars() {
        return numberOfCars;
    }

    /**
     * Sets the value of the numberOfCars property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfCars(BigInteger value) {
        this.numberOfCars = value;
    }

    /**
     * Gets the value of the birthYearChild1 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthYearChild1() {
        return birthYearChild1;
    }

    /**
     * Sets the value of the birthYearChild1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthYearChild1(XMLGregorianCalendar value) {
        this.birthYearChild1 = value;
    }

    /**
     * Gets the value of the birthYearChild2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthYearChild2() {
        return birthYearChild2;
    }

    /**
     * Sets the value of the birthYearChild2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthYearChild2(XMLGregorianCalendar value) {
        this.birthYearChild2 = value;
    }

    /**
     * Gets the value of the birthYearChild3 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthYearChild3() {
        return birthYearChild3;
    }

    /**
     * Sets the value of the birthYearChild3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthYearChild3(XMLGregorianCalendar value) {
        this.birthYearChild3 = value;
    }

    /**
     * Gets the value of the birthYearChild4 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthYearChild4() {
        return birthYearChild4;
    }

    /**
     * Sets the value of the birthYearChild4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthYearChild4(XMLGregorianCalendar value) {
        this.birthYearChild4 = value;
    }

    /**
     * Gets the value of the additionalMemberFor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalMemberFor() {
        return additionalMemberFor;
    }

    /**
     * Sets the value of the additionalMemberFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalMemberFor(String value) {
        this.additionalMemberFor = value;
    }

}
