//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 04:53:43 PM CDT 
//


package com.cencosud.middleware.bonus.client.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MemberPreferencesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MemberPreferencesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CouldBeContacted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ContactedForMarketResearch" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ContactedByEMail" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ContactByPhone" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ContactByMail" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="NoRestrictionInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MemberPreferencesType", namespace = "http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember", propOrder = {
    "couldBeContacted",
    "contactedForMarketResearch",
    "contactedByEMail",
    "contactByPhone",
    "contactByMail",
    "noRestrictionInfo"
})
public class MemberPreferencesType {

    @XmlElement(name = "CouldBeContacted")
    protected Boolean couldBeContacted;
    @XmlElement(name = "ContactedForMarketResearch")
    protected Boolean contactedForMarketResearch;
    @XmlElement(name = "ContactedByEMail")
    protected Boolean contactedByEMail;
    @XmlElement(name = "ContactByPhone")
    protected Boolean contactByPhone;
    @XmlElement(name = "ContactByMail")
    protected Boolean contactByMail;
    @XmlElement(name = "NoRestrictionInfo")
    protected Boolean noRestrictionInfo;

    /**
     * Gets the value of the couldBeContacted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCouldBeContacted() {
        return couldBeContacted;
    }

    /**
     * Sets the value of the couldBeContacted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCouldBeContacted(Boolean value) {
        this.couldBeContacted = value;
    }

    /**
     * Gets the value of the contactedForMarketResearch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContactedForMarketResearch() {
        return contactedForMarketResearch;
    }

    /**
     * Sets the value of the contactedForMarketResearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContactedForMarketResearch(Boolean value) {
        this.contactedForMarketResearch = value;
    }

    /**
     * Gets the value of the contactedByEMail property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContactedByEMail() {
        return contactedByEMail;
    }

    /**
     * Sets the value of the contactedByEMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContactedByEMail(Boolean value) {
        this.contactedByEMail = value;
    }

    /**
     * Gets the value of the contactByPhone property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContactByPhone() {
        return contactByPhone;
    }

    /**
     * Sets the value of the contactByPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContactByPhone(Boolean value) {
        this.contactByPhone = value;
    }

    /**
     * Gets the value of the contactByMail property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContactByMail() {
        return contactByMail;
    }

    /**
     * Sets the value of the contactByMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContactByMail(Boolean value) {
        this.contactByMail = value;
    }

    /**
     * Gets the value of the noRestrictionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoRestrictionInfo() {
        return noRestrictionInfo;
    }

    /**
     * Sets the value of the noRestrictionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoRestrictionInfo(Boolean value) {
        this.noRestrictionInfo = value;
    }

}
