//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 04:53:43 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.cencosud.corp/Loyalty/Core/EBM/LoyaltyMember", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cencosud.middleware.bonus.client.wsdl;
