//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 04:53:43 PM CDT 
//


package com.cencosud.middleware.bonus.client.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryMemberSegmentsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryMemberSegmentsResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MemberSegments"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Segment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Segment1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryMemberSegmentsResponseType", propOrder = {
    "memberSegments"
})
public class QueryMemberSegmentsResponseType {

    @XmlElement(name = "MemberSegments", required = true)
    protected QueryMemberSegmentsResponseType.MemberSegments memberSegments;

    /**
     * Gets the value of the memberSegments property.
     * 
     * @return
     *     possible object is
     *     {@link QueryMemberSegmentsResponseType.MemberSegments }
     *     
     */
    public QueryMemberSegmentsResponseType.MemberSegments getMemberSegments() {
        return memberSegments;
    }

    /**
     * Sets the value of the memberSegments property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryMemberSegmentsResponseType.MemberSegments }
     *     
     */
    public void setMemberSegments(QueryMemberSegmentsResponseType.MemberSegments value) {
        this.memberSegments = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Segment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Segment1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "segment",
        "segment1"
    })
    public static class MemberSegments {

        @XmlElement(name = "Segment", required = true)
        protected String segment;
        @XmlElement(name = "Segment1", required = true)
        protected String segment1;

        /**
         * Gets the value of the segment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSegment() {
            return segment;
        }

        /**
         * Sets the value of the segment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSegment(String value) {
            this.segment = value;
        }

        /**
         * Gets the value of the segment1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSegment1() {
            return segment1;
        }

        /**
         * Sets the value of the segment1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSegment1(String value) {
            this.segment1 = value;
        }

    }

}
