//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 04:53:43 PM CDT 
//


package com.cencosud.middleware.bonus.client.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryLoyaltyMemberFullResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryLoyaltyMemberFullResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="QueryLoyaltyMember" type="{http://xmlns.cencosud.corp/Loyalty/Core/EBO/LoyaltyMember}LoyaltyMemberFullType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryLoyaltyMemberFullResponseType", propOrder = {
    "queryLoyaltyMember"
})
public class QueryLoyaltyMemberFullResponseType {

    @XmlElement(name = "QueryLoyaltyMember", required = true)
    protected LoyaltyMemberFullType queryLoyaltyMember;

    /**
     * Gets the value of the queryLoyaltyMember property.
     * 
     * @return
     *     possible object is
     *     {@link LoyaltyMemberFullType }
     *     
     */
    public LoyaltyMemberFullType getQueryLoyaltyMember() {
        return queryLoyaltyMember;
    }

    /**
     * Sets the value of the queryLoyaltyMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoyaltyMemberFullType }
     *     
     */
    public void setQueryLoyaltyMember(LoyaltyMemberFullType value) {
        this.queryLoyaltyMember = value;
    }

}
