vtex:
  schema: http
  url: "jumbo.vtexcommercestable.com.br"
  port: "80"
  apiKey: "vtexappkey-jumbo-DEYICH"
  apiSecret: "MWDTHGQLSKANIZPSYXQCXBVNKAYDWNWNLYBFGXQELAHMCSIRPACEDYPKBQIHINPFOMCKXJLBGMQXUILRSGNWKRKMIQDQOJWYLBYPQYTGOBXQISQSFQPBZTUWCQCHFVMX"

security:
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb
    
endpoints:
    enabled: false
    health:
        enabled: true
