vtex:
  schema: http
  url: "jumbochilehomolog.vtexcommercestable.com.br"
  port: "80"
  apiKey: "ignacio.contreras.cencosud@gmail.com"
  apiSecret: "8P9HJ8Sr"

security:
  require-ssl: false
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb
    
endpoints:
    enabled: false
    health:
        enabled: true