twitter:
  android:
    consumerKey: "knJVYYGgGFlVPOxT06GAUSqah"
    consumerSecretKey: "zSOm7CgwOQxeMqbYYC8oxXSlREj6TEWxG6DySp2kJ698J1deEU"
  ios:
    consumerKey: "knJVYYGgGFlVPOxT06GAUSqah"
    consumerSecretKey: "zSOm7CgwOQxeMqbYYC8oxXSlREj6TEWxG6DySp2kJ698J1deEU"
logging:
  level:
    org.springframework.web: DEBUG
    com.cencosud.middleware.login: DEBUG