//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 02:50:25 PM UYT 
//


package com.cencosud.middleware.rewards.client.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Comercio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Tipdoccod" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="Prsnrodoc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Fechatransaccion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Horatransaccion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Pos_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "comercio",
    "tipdoccod",
    "prsnrodoc",
    "fechatransaccion",
    "horatransaccion",
    "posId"
})
@XmlRootElement(name = "WSCDCen.Execute")
public class WSCDCenExecute {

    @XmlElement(name = "Comercio", required = true)
    protected String comercio;
    @XmlElement(name = "Tipdoccod")
    protected short tipdoccod;
    @XmlElement(name = "Prsnrodoc", required = true)
    protected String prsnrodoc;
    @XmlElement(name = "Fechatransaccion", required = true)
    protected String fechatransaccion;
    @XmlElement(name = "Horatransaccion", required = true)
    protected String horatransaccion;
    @XmlElement(name = "Pos_id", required = true)
    protected String posId;

    /**
     * Gets the value of the comercio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComercio() {
        return comercio;
    }

    /**
     * Sets the value of the comercio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComercio(String value) {
        this.comercio = value;
    }

    /**
     * Gets the value of the tipdoccod property.
     * 
     */
    public short getTipdoccod() {
        return tipdoccod;
    }

    /**
     * Sets the value of the tipdoccod property.
     * 
     */
    public void setTipdoccod(short value) {
        this.tipdoccod = value;
    }

    /**
     * Gets the value of the prsnrodoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrsnrodoc() {
        return prsnrodoc;
    }

    /**
     * Sets the value of the prsnrodoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrsnrodoc(String value) {
        this.prsnrodoc = value;
    }

    /**
     * Gets the value of the fechatransaccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechatransaccion() {
        return fechatransaccion;
    }

    /**
     * Sets the value of the fechatransaccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechatransaccion(String value) {
        this.fechatransaccion = value;
    }

    /**
     * Gets the value of the horatransaccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoratransaccion() {
        return horatransaccion;
    }

    /**
     * Sets the value of the horatransaccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoratransaccion(String value) {
        this.horatransaccion = value;
    }

    /**
     * Gets the value of the posId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosId() {
        return posId;
    }

    /**
     * Sets the value of the posId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosId(String value) {
        this.posId = value;
    }

}
