//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 02:50:25 PM UYT 
//


package com.cencosud.middleware.rewards.client.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="O_nombrecompleto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_nrodocumento" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_saldopuntos" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_puntosvencidos" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_flagtarjetaerrada" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_flagdatoserrados" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_flagnrodocerrado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_flagfechanacimientoerrada" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_flagemailerrado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_flagtelefonoerrado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_flagdireccionerrada" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_flaganiversariobonus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_flagonomastico" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_frecuenciavisita" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_flagsospechafraude" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_flagcomercioerrado" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_tarjetapadre" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_mensajeerror" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="O_error" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oNombrecompleto",
    "oNrodocumento",
    "oSaldopuntos",
    "oPuntosvencidos",
    "oFlagtarjetaerrada",
    "oFlagdatoserrados",
    "oFlagnrodocerrado",
    "oFlagfechanacimientoerrada",
    "oFlagemailerrado",
    "oFlagtelefonoerrado",
    "oFlagdireccionerrada",
    "oFlaganiversariobonus",
    "oFlagonomastico",
    "oFrecuenciavisita",
    "oFlagsospechafraude",
    "oFlagcomercioerrado",
    "oTarjetapadre",
    "oMensajeerror",
    "oError"
})
@XmlRootElement(name = "WSCDCen.ExecuteResponse")
public class WSCDCenExecuteResponse {

    @XmlElement(name = "O_nombrecompleto", required = true)
    protected String oNombrecompleto;
    @XmlElement(name = "O_nrodocumento", required = true)
    protected String oNrodocumento;
    @XmlElement(name = "O_saldopuntos", required = true)
    protected String oSaldopuntos;
    @XmlElement(name = "O_puntosvencidos", required = true)
    protected String oPuntosvencidos;
    @XmlElement(name = "O_flagtarjetaerrada", required = true)
    protected String oFlagtarjetaerrada;
    @XmlElement(name = "O_flagdatoserrados", required = true)
    protected String oFlagdatoserrados;
    @XmlElement(name = "O_flagnrodocerrado", required = true)
    protected String oFlagnrodocerrado;
    @XmlElement(name = "O_flagfechanacimientoerrada", required = true)
    protected String oFlagfechanacimientoerrada;
    @XmlElement(name = "O_flagemailerrado", required = true)
    protected String oFlagemailerrado;
    @XmlElement(name = "O_flagtelefonoerrado", required = true)
    protected String oFlagtelefonoerrado;
    @XmlElement(name = "O_flagdireccionerrada", required = true)
    protected String oFlagdireccionerrada;
    @XmlElement(name = "O_flaganiversariobonus", required = true)
    protected String oFlaganiversariobonus;
    @XmlElement(name = "O_flagonomastico", required = true)
    protected String oFlagonomastico;
    @XmlElement(name = "O_frecuenciavisita", required = true)
    protected String oFrecuenciavisita;
    @XmlElement(name = "O_flagsospechafraude", required = true)
    protected String oFlagsospechafraude;
    @XmlElement(name = "O_flagcomercioerrado", required = true)
    protected String oFlagcomercioerrado;
    @XmlElement(name = "O_tarjetapadre", required = true)
    protected String oTarjetapadre;
    @XmlElement(name = "O_mensajeerror", required = true)
    protected String oMensajeerror;
    @XmlElement(name = "O_error")
    protected byte oError;

    /**
     * Gets the value of the oNombrecompleto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getONombrecompleto() {
        return oNombrecompleto;
    }

    /**
     * Sets the value of the oNombrecompleto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setONombrecompleto(String value) {
        this.oNombrecompleto = value;
    }

    /**
     * Gets the value of the oNrodocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getONrodocumento() {
        return oNrodocumento;
    }

    /**
     * Sets the value of the oNrodocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setONrodocumento(String value) {
        this.oNrodocumento = value;
    }

    /**
     * Gets the value of the oSaldopuntos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSaldopuntos() {
        return oSaldopuntos;
    }

    /**
     * Sets the value of the oSaldopuntos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSaldopuntos(String value) {
        this.oSaldopuntos = value;
    }

    /**
     * Gets the value of the oPuntosvencidos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPuntosvencidos() {
        return oPuntosvencidos;
    }

    /**
     * Sets the value of the oPuntosvencidos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPuntosvencidos(String value) {
        this.oPuntosvencidos = value;
    }

    /**
     * Gets the value of the oFlagtarjetaerrada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFlagtarjetaerrada() {
        return oFlagtarjetaerrada;
    }

    /**
     * Sets the value of the oFlagtarjetaerrada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFlagtarjetaerrada(String value) {
        this.oFlagtarjetaerrada = value;
    }

    /**
     * Gets the value of the oFlagdatoserrados property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFlagdatoserrados() {
        return oFlagdatoserrados;
    }

    /**
     * Sets the value of the oFlagdatoserrados property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFlagdatoserrados(String value) {
        this.oFlagdatoserrados = value;
    }

    /**
     * Gets the value of the oFlagnrodocerrado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFlagnrodocerrado() {
        return oFlagnrodocerrado;
    }

    /**
     * Sets the value of the oFlagnrodocerrado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFlagnrodocerrado(String value) {
        this.oFlagnrodocerrado = value;
    }

    /**
     * Gets the value of the oFlagfechanacimientoerrada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFlagfechanacimientoerrada() {
        return oFlagfechanacimientoerrada;
    }

    /**
     * Sets the value of the oFlagfechanacimientoerrada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFlagfechanacimientoerrada(String value) {
        this.oFlagfechanacimientoerrada = value;
    }

    /**
     * Gets the value of the oFlagemailerrado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFlagemailerrado() {
        return oFlagemailerrado;
    }

    /**
     * Sets the value of the oFlagemailerrado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFlagemailerrado(String value) {
        this.oFlagemailerrado = value;
    }

    /**
     * Gets the value of the oFlagtelefonoerrado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFlagtelefonoerrado() {
        return oFlagtelefonoerrado;
    }

    /**
     * Sets the value of the oFlagtelefonoerrado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFlagtelefonoerrado(String value) {
        this.oFlagtelefonoerrado = value;
    }

    /**
     * Gets the value of the oFlagdireccionerrada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFlagdireccionerrada() {
        return oFlagdireccionerrada;
    }

    /**
     * Sets the value of the oFlagdireccionerrada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFlagdireccionerrada(String value) {
        this.oFlagdireccionerrada = value;
    }

    /**
     * Gets the value of the oFlaganiversariobonus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFlaganiversariobonus() {
        return oFlaganiversariobonus;
    }

    /**
     * Sets the value of the oFlaganiversariobonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFlaganiversariobonus(String value) {
        this.oFlaganiversariobonus = value;
    }

    /**
     * Gets the value of the oFlagonomastico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFlagonomastico() {
        return oFlagonomastico;
    }

    /**
     * Sets the value of the oFlagonomastico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFlagonomastico(String value) {
        this.oFlagonomastico = value;
    }

    /**
     * Gets the value of the oFrecuenciavisita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFrecuenciavisita() {
        return oFrecuenciavisita;
    }

    /**
     * Sets the value of the oFrecuenciavisita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFrecuenciavisita(String value) {
        this.oFrecuenciavisita = value;
    }

    /**
     * Gets the value of the oFlagsospechafraude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFlagsospechafraude() {
        return oFlagsospechafraude;
    }

    /**
     * Sets the value of the oFlagsospechafraude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFlagsospechafraude(String value) {
        this.oFlagsospechafraude = value;
    }

    /**
     * Gets the value of the oFlagcomercioerrado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFlagcomercioerrado() {
        return oFlagcomercioerrado;
    }

    /**
     * Sets the value of the oFlagcomercioerrado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFlagcomercioerrado(String value) {
        this.oFlagcomercioerrado = value;
    }

    /**
     * Gets the value of the oTarjetapadre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTarjetapadre() {
        return oTarjetapadre;
    }

    /**
     * Sets the value of the oTarjetapadre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTarjetapadre(String value) {
        this.oTarjetapadre = value;
    }

    /**
     * Gets the value of the oMensajeerror property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOMensajeerror() {
        return oMensajeerror;
    }

    /**
     * Sets the value of the oMensajeerror property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOMensajeerror(String value) {
        this.oMensajeerror = value;
    }

    /**
     * Gets the value of the oError property.
     * 
     */
    public byte getOError() {
        return oError;
    }

    /**
     * Sets the value of the oError property.
     * 
     */
    public void setOError(byte value) {
        this.oError = value;
    }

}
