vtex:
  schema: http
  url: "jumbochilehomolog.vtexcommercestable.com.br"
  port: "80"
  apiKey: "vtexappkey-jumbochilehomolog-IAMKWV"
  apiSecret: "RSRVBUIUVTMVEPPXIRIWPYWEIYSJQHSTWYPASGFFFRASOZDBBYCGWOYTWMNDBYENASZFAOFCMCRXXEPJURHREMXHAWEFSBDGNMRWZYBNTZTTWBVSWDJKQMJOVRFDKZJK"

security:
  require-ssl: false
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb
    
endpoints:
    enabled: false
    health:
        enabled: true