vtex:
  schema: http
  url: "wong.vtexcommercestable.com.br"
  port: "80"
  apiKey: "vtexappkey-wong-QQJIUC"
  apiSecret: "ZIOSACOASSPPZBGDWXCAYSJYNZEHEIQIRMNXKJPQUOKOZKZJCWFCHICHYPFAYHWJCGYMNJSMIMGJIVYCAUFICOBIKGYUEOSMRBLSMMVSDSUVCSYDRCZDCOGOFPCHLYIT"
  env: prod
mongoConfig:
  database: "categories"
business:
  departmentsIds:
    - "1000144"
    - "1000003"
    - "1000131"
    - "1000069"
    - "1000143"

  departments:
    1000144: {id: "1000144", name: "Tecnolog\u00EDa", basicPath: "/tecnologia", order: "0"}
    1000143: {id: "1000143", name: "Ni\u00F1os y Beb\u00E9s", basicPath: "/ninos-y-bebes", order: "4"}
    1000003: {id: "1000003", name: "Electrodom\u00e9sticos", basicPath: "/electro", order: "1"}
    1000131: {id: "1000131", name: "Hogar", basicPath: "/hogar", order: "2"}
    1000069: {id: "1000069", name: "Deportes", basicPath: "/deportes", order: "3"}

server:
  path: "https://cenco-categories-service.mybluemix.net/"
security:
  require-ssl: true
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb

endpoints:
    enabled: false
    health:
        enabled: true