documentValidateRegex: ^[0-9]{7,8}$

awsProperties:
  secretKey: GiblY5MJzkTDNgN7+3SS5GUldZmia7J1IhAKO5MY
  accessKey: AKIAIX65WL7JV3MEOD7A
  region: us-east-1
  
security:
  require-ssl: false
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb