chaordic:
  schema: http
  url: "recs.chaordicsystems.com"
  apiKey: "wong"
  apiSecret: "N1E+1lLZybhosJe4KBKFsA=="
  defaultProductId: "525052"
  defaultProductSearchType: "Similar"
  defaultCategorySearchType: "BestSellers"
  baseUrlImages: "http://tienda.wong.com.pe"
mongoConfig:
  database: "recommendations"
security:
  require-ssl: true
  user:
    name: cencoappuser
    password: HjztW7dQL7Y8XJ5cZbpfgMHb
          
endpoints:
    enabled: false
    health:
        enabled: true